### ISSUE TITLE
Crash at clientstart on latest release

### ISSUE THREAD

**Issue by TheButterbrotMan** [AfraidMonster/more-doors#1]
https://bytebin.lucko.me/4A3gyzYlkh

**Comment by AfraidMonster** [comment]
Does this only happen when more doors is loaded?

**Comment by AfraidMonster** [comment]
I cant seem to re-create this issue on my own, could you send me the moredoors java file you're using? Thnaks

**Comment by TheButterbrotMan** [comment]
[more-doors-1.18.2.jar.zip](https://github.com/AfraidMonster/more-doors/files/9228094/more-doors-1.18.2.jar.zip)
